version: "3.8"
services:
    mysqldb:
      container_name: mysqldb
      image: mysql
      #command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        #MYSQL_ALLOW_EMPTY_PASSWORD: true
        #MYSQL_DATABASE: businessassistantbcndb
        #MYSQL_USER: root 
        #MYSQL_PASSWORD: 
volumes:
  data: {}
    
networks:
    default:
        name: mysqldb_network