--DROP TABLE IF EXISTS jugador;

--DROP TABLE IF EXISTS juego;
--DROP TABLE IF EXISTS dado;


CREATE TABLE IF NOT EXISTS jugador (
	id_jugador INTEGER NOT NULL AUTO_INCREMENT,
	fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	nombre VARCHAR(250) NOT NULL,
	ratio DECIMAL NOT NULL DEFAULT 0.0,
	PRIMARY KEY (id_jugador)
);

CREATE TABLE IF NOT EXISTS juego (
	id_juego INTEGER NOT NULL AUTO_INCREMENT,
	id_jugador INTEGER NOT NULL,
	dado1 INTEGER NOT NULL,
	dado2 INTEGER NOT NULL,
	resultado INTEGER NOT NULL,
	PRIMARY KEY (id_juego),
	FOREIGN KEY (id_jugador) REFERENCES jugador(id_jugador) ON DELETE CASCADE ON UPDATE CASCADE
);